version: '3.8'

services:
  smallproject:
    image: smallproject:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:9090;https://+9091
      ConnectionStrings__DefaultConnection: ${DATABASE_CONNECTION_STRING}
    networks:
      - smallproject-network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

networks:
  smallproject-network:
    driver: overlay
